# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='locales',
            new_name='local',
        ),
    ]
