# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160413_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunidadAutonoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('idCCAA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComunidadAutonoma')),
            ],
        ),
        migrations.CreateModel(
            name='rutas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('enlaceRuta', models.CharField(max_length=250)),
                ('idProvincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Provincia')),
            ],
        ),
        migrations.DeleteModel(
            name='local',
        ),
    ]
